title: Vienna Blog
author: Alice Lee
url: https://alicel.ee
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)

remote_theme: riggraz/no-style-please
theme: no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
#plugins:
#        - jekyll-feed
